import type { Product } from "@/types/product.types"

// Imagen de Instagram para todos los productos
const instagramImage =
  "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/DALL_E2024-05-2405.21.06-Asquareaspectratioimagefeaturinga3DInstagramlogoinspiredbytheprovidedreference.ThelogohastheclassicInstagramgradientwiththewhi-GGFMEpsfFM6U4tiP1Bge0shInCOSgy.jpeg"

// Texto de garantía para incluir en las descripciones
const garantiaText = "Con 30 días de garantía ante caídas (1% ~ 5%)."

export const instagramServicesData: Product[] = [
  // Seguidores de Calidad para Instagram
  {
    id: 101,
    title: "100 Seguidores Instagram",
    description: `Seguidores de calidad mundial para tu cuenta. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 1800,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.9,
    platform: "instagram",
    category: "seguidores",
  },
  {
    id: 102,
    title: "250 Seguidores Instagram",
    description: `Seguidores de calidad mundial para tu cuenta. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 3500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.9,
    platform: "instagram",
    category: "seguidores",
  },
  {
    id: 103,
    title: "500 Seguidores Instagram",
    description: `Seguidores de calidad mundial para tu cuenta. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 6500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.9,
    platform: "instagram",
    category: "seguidores",
  },
  {
    id: 104,
    title: "1.000 Seguidores Instagram",
    description: `Seguidores de calidad mundial para tu cuenta. Incluye 250 Likes de regalo. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 12000,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 5.0,
    platform: "instagram",
    category: "seguidores",
  },
  {
    id: 105,
    title: "2.500 Seguidores Instagram",
    description: `Seguidores de calidad mundial para tu cuenta. Incluye 500 Likes de regalo. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 30000,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 5.0,
    platform: "instagram",
    category: "seguidores",
  },
  {
    id: 106,
    title: "5.000 Seguidores Instagram",
    description: `Seguidores de calidad mundial para tu cuenta. Incluye 1.000 Likes y 1.000 Visitas de regalo. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 60000,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 5.0,
    platform: "instagram",
    category: "seguidores",
  },
  {
    id: 107,
    title: "10.000 Seguidores Instagram",
    description: `Seguidores de calidad mundial para tu cuenta. Incluye 2.000 Likes y 2.000 Visitas de regalo. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 120000,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 5.0,
    platform: "instagram",
    category: "seguidores",
  },

  // Likes de Calidad para Instagram
  {
    id: 201,
    title: "50 Likes Instagram",
    description: `Likes de calidad mundial para tus publicaciones. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.8,
    platform: "instagram",
    category: "likes",
  },
  {
    id: 202,
    title: "100 Likes Instagram",
    description: `Likes de calidad mundial para tus publicaciones. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 800,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.8,
    platform: "instagram",
    category: "likes",
  },
  {
    id: 203,
    title: "250 Likes Instagram",
    description: `Likes de calidad mundial para tus publicaciones. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 1500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.8,
    platform: "instagram",
    category: "likes",
  },
  {
    id: 204,
    title: "500 Likes Instagram",
    description: `Likes de calidad mundial para tus publicaciones. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 2500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.9,
    platform: "instagram",
    category: "likes",
  },
  {
    id: 205,
    title: "1.000 Likes Instagram",
    description: `Likes de calidad mundial para tus publicaciones. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 4500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.9,
    platform: "instagram",
    category: "likes",
  },
  {
    id: 206,
    title: "2.500 Likes Instagram",
    description: `Likes de calidad mundial para tus publicaciones. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 7500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 5.0,
    platform: "instagram",
    category: "likes",
  },
  {
    id: 207,
    title: "5.000 Likes Instagram",
    description: `Likes de calidad mundial para tus publicaciones. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 12000,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 5.0,
    platform: "instagram",
    category: "likes",
  },
  {
    id: 208,
    title: "10.000 Likes Instagram",
    description: `Likes de calidad mundial para tus publicaciones. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 20000,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 5.0,
    platform: "instagram",
    category: "likes",
  },

  // Visitas Mundiales para Instagram
  {
    id: 301,
    title: "500 Visitas Instagram",
    description: `Visitas mundiales para aumentar el alcance de tus publicaciones. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 250,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.7,
    platform: "instagram",
    category: "visitas",
  },
  {
    id: 302,
    title: "1.000 Visitas Instagram",
    description: `Visitas mundiales para aumentar el alcance de tus publicaciones. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.7,
    platform: "instagram",
    category: "visitas",
  },
  {
    id: 303,
    title: "2.500 Visitas Instagram",
    description: `Visitas mundiales para aumentar el alcance de tus publicaciones. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 1500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.8,
    platform: "instagram",
    category: "visitas",
  },
  {
    id: 304,
    title: "5.000 Visitas Instagram",
    description: `Visitas mundiales para aumentar el alcance de tus publicaciones. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 2500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.8,
    platform: "instagram",
    category: "visitas",
  },
  {
    id: 305,
    title: "10.000 Visitas Instagram",
    description: `Visitas mundiales para aumentar el alcance de tus publicaciones. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 4500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.9,
    platform: "instagram",
    category: "visitas",
  },

  // Visitas a historias
  {
    id: 401,
    title: "100 Visitas a Historias",
    description: `Aumenta la visibilidad de tus historias de Instagram. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 150,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.7,
    platform: "instagram",
    category: "historias",
  },
  {
    id: 402,
    title: "250 Visitas a Historias",
    description: `Aumenta la visibilidad de tus historias de Instagram. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 400,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.7,
    platform: "instagram",
    category: "historias",
  },
  {
    id: 403,
    title: "500 Visitas a Historias",
    description: `Aumenta la visibilidad de tus historias de Instagram. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 800,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.8,
    platform: "instagram",
    category: "historias",
  },
  {
    id: 404,
    title: "1.000 Visitas a Historias",
    description: `Aumenta la visibilidad de tus historias de Instagram. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 1500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.8,
    platform: "instagram",
    category: "historias",
  },
  {
    id: 405,
    title: "2.500 Visitas a Historias",
    description: `Aumenta la visibilidad de tus historias de Instagram. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 3500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.9,
    platform: "instagram",
    category: "historias",
  },
  {
    id: 406,
    title: "5.000 Visitas a Historias",
    description: `Aumenta la visibilidad de tus historias de Instagram. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 6000,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.9,
    platform: "instagram",
    category: "historias",
  },
  {
    id: 407,
    title: "10.000 Visitas a Historias",
    description: `Aumenta la visibilidad de tus historias de Instagram. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 10000,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 5.0,
    platform: "instagram",
    category: "historias",
  },

  // Guardados de Post
  {
    id: 501,
    title: "250 Guardados de Post",
    description: `Incrementa los guardados en tus publicaciones para mejorar el algoritmo. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 400,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.7,
    platform: "instagram",
    category: "guardados",
  },
  {
    id: 502,
    title: "500 Guardados de Post",
    description: `Incrementa los guardados en tus publicaciones para mejorar el algoritmo. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 800,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.8,
    platform: "instagram",
    category: "guardados",
  },
  {
    id: 503,
    title: "1.000 Guardados de Post",
    description: `Incrementa los guardados en tus publicaciones para mejorar el algoritmo. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 1500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.8,
    platform: "instagram",
    category: "guardados",
  },
  {
    id: 504,
    title: "2.500 Guardados de Post",
    description: `Incrementa los guardados en tus publicaciones para mejorar el algoritmo. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 3500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.9,
    platform: "instagram",
    category: "guardados",
  },
  {
    id: 505,
    title: "5.000 Guardados de Post",
    description: `Incrementa los guardados en tus publicaciones para mejorar el algoritmo. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 6000,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.9,
    platform: "instagram",
    category: "guardados",
  },
  {
    id: 506,
    title: "10.000 Guardados de Post",
    description: `Incrementa los guardados en tus publicaciones para mejorar el algoritmo. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 10000,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 5.0,
    platform: "instagram",
    category: "guardados",
  },

  // Comentarios Random
  {
    id: 601,
    title: "10 Comentarios Random",
    description: `Comentarios aleatorios positivos para tus publicaciones. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 2000,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.8,
    platform: "instagram",
    category: "comentarios",
  },
  {
    id: 602,
    title: "50 Comentarios Random",
    description: `Comentarios aleatorios positivos para tus publicaciones. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 4500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.9,
    platform: "instagram",
    category: "comentarios",
  },
  {
    id: 603,
    title: "100 Comentarios Random",
    description: `Comentarios aleatorios positivos para tus publicaciones. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 7500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.9,
    platform: "instagram",
    category: "comentarios",
  },
  {
    id: 604,
    title: "500 Comentarios Random",
    description: `Comentarios aleatorios positivos para tus publicaciones. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 15000,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 5.0,
    platform: "instagram",
    category: "comentarios",
  },
  {
    id: 605,
    title: "1.000 Comentarios Random",
    description: `Comentarios aleatorios positivos para tus publicaciones. ${garantiaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 25000,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 5.0,
    platform: "instagram",
    category: "comentarios",
  },
]

// Categorías de servicios de Instagram
export const instagramCategories = [
  { id: "seguidores", name: "Seguidores de Calidad" },
  { id: "likes", name: "Likes de Calidad" },
  { id: "visitas", name: "Visitas Mundiales" },
  { id: "historias", name: "Visitas a Historias" },
  { id: "guardados", name: "Guardados de Post" },
  { id: "comentarios", name: "Comentarios Random" },
]

// Obtener productos por categoría
export const getProductsByCategory = (category: string) => {
  return instagramServicesData.filter((product) => product.category === category)
}

