import type { Product } from "@/types/product.types"

// Imagen de Instagram para todos los productos
const instagramImage =
  "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/DALL_E2024-05-2405.21.06-Asquareaspectratioimagefeaturinga3DInstagramlogoinspiredbytheprovidedreference.ThelogohastheclassicInstagramgradientwiththewhi-GGFMEpsfFM6U4tiP1Bge0shInCOSgy.jpeg"

// Texto de advertencia para incluir en las descripciones
const advertenciaText = "No cuenta con garantía por caídas. Caída de seguidores de 10% ~ 30%."

export const instagramServicesData: Product[] = [
  // SEGUIDORES DE CALIDAD PARA INSTAGRAM
  {
    id: 101,
    title: "100 Seguidores de Calidad",
    description: `Seguidores de calidad mundial para tu cuenta. Con 30 días de garantía ante caídas (1% ~ 5%).`,
    longDescription: `Aumenta tu credibilidad en Instagram con seguidores de calidad mundial. Este paquete incluye 100 seguidores reales y activos que se entregarán de forma gradual para mantener la naturalidad de tu cuenta. Todos nuestros seguidores de calidad incluyen 30 días de garantía ante caídas (solo 1% ~ 5%).`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 1800,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.9,
    platform: "instagram",
    category: "seguidores-calidad",
    features: [
      "100 seguidores reales y activos",
      "Entrega gradual y natural",
      "30 días de garantía",
      "Caídas mínimas (1-5%)",
      "Soporte 24/7",
    ],
  },
  {
    id: 102,
    title: "250 Seguidores de Calidad",
    description: `Seguidores de calidad mundial para tu cuenta. Con 30 días de garantía ante caídas (1% ~ 5%).`,
    longDescription: `Aumenta tu credibilidad en Instagram con seguidores de calidad mundial. Este paquete incluye 250 seguidores reales y activos que se entregarán de forma gradual para mantener la naturalidad de tu cuenta. Todos nuestros seguidores de calidad incluyen 30 días de garantía ante caídas (solo 1% ~ 5%).`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 3500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.9,
    platform: "instagram",
    category: "seguidores-calidad",
    features: [
      "250 seguidores reales y activos",
      "Entrega gradual y natural",
      "30 días de garantía",
      "Caídas mínimas (1-5%)",
      "Soporte 24/7",
    ],
  },
  {
    id: 103,
    title: "500 Seguidores de Calidad",
    description: `Seguidores de calidad mundial para tu cuenta. Con 30 días de garantía ante caídas (1% ~ 5%).`,
    longDescription: `Aumenta tu credibilidad en Instagram con seguidores de calidad mundial. Este paquete incluye 500 seguidores reales y activos que se entregarán de forma gradual para mantener la naturalidad de tu cuenta. Todos nuestros seguidores de calidad incluyen 30 días de garantía ante caídas (solo 1% ~ 5%).`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 6500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.9,
    platform: "instagram",
    category: "seguidores-calidad",
    features: [
      "500 seguidores reales y activos",
      "Entrega gradual y natural",
      "30 días de garantía",
      "Caídas mínimas (1-5%)",
      "Soporte 24/7",
    ],
  },
  {
    id: 104,
    title: "1.000 Seguidores de Calidad",
    description: `Seguidores de calidad mundial para tu cuenta. Incluye 250 Likes de regalo. Con 30 días de garantía ante caídas (1% ~ 5%).`,
    longDescription: `Aumenta tu credibilidad en Instagram con seguidores de calidad mundial. Este paquete incluye 1.000 seguidores reales y activos que se entregarán de forma gradual para mantener la naturalidad de tu cuenta. Como BONUS, recibirás 250 likes para tus publicaciones. Todos nuestros seguidores de calidad incluyen 30 días de garantía ante caídas (solo 1% ~ 5%).`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 12000,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 5.0,
    platform: "instagram",
    category: "seguidores-calidad",
    features: [
      "1.000 seguidores reales y activos",
      "BONUS: 250 likes para tus publicaciones",
      "Entrega gradual y natural",
      "30 días de garantía",
      "Caídas mínimas (1-5%)",
      "Soporte 24/7",
    ],
  },
  {
    id: 105,
    title: "2.500 Seguidores de Calidad",
    description: `Seguidores de calidad mundial para tu cuenta. Incluye 500 Likes de regalo. Con 30 días de garantía ante caídas (1% ~ 5%).`,
    longDescription: `Aumenta tu credibilidad en Instagram con seguidores de calidad mundial. Este paquete incluye 2.500 seguidores reales y activos que se entregarán de forma gradual para mantener la naturalidad de tu cuenta. Como BONUS, recibirás 500 likes para tus publicaciones. Todos nuestros seguidores de calidad incluyen 30 días de garantía ante caídas (solo 1% ~ 5%).`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 30000,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 5.0,
    platform: "instagram",
    category: "seguidores-calidad",
    features: [
      "2.500 seguidores reales y activos",
      "BONUS: 500 likes para tus publicaciones",
      "Entrega gradual y natural",
      "30 días de garantía",
      "Caídas mínimas (1-5%)",
      "Soporte 24/7",
    ],
  },
  {
    id: 106,
    title: "5.000 Seguidores de Calidad",
    description: `Seguidores de calidad mundial para tu cuenta. Incluye 1.000 Likes y 1.000 Visitas de regalo. Con 30 días de garantía ante caídas (1% ~ 5%).`,
    longDescription: `Aumenta tu credibilidad en Instagram con seguidores de calidad mundial. Este paquete incluye 5.000 seguidores reales y activos que se entregarán de forma gradual para mantener la naturalidad de tu cuenta. Como BONUS, recibirás 1.000 likes y 1.000 visitas para tus publicaciones. Todos nuestros seguidores de calidad incluyen 30 días de garantía ante caídas (solo 1% ~ 5%).`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 60000,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 5.0,
    platform: "instagram",
    category: "seguidores-calidad",
    features: [
      "5.000 seguidores reales y activos",
      "BONUS: 1.000 likes para tus publicaciones",
      "BONUS: 1.000 visitas para tus publicaciones",
      "Entrega gradual y natural",
      "30 días de garantía",
      "Caídas mínimas (1-5%)",
      "Soporte 24/7",
    ],
  },
  {
    id: 107,
    title: "10.000 Seguidores de Calidad",
    description: `Seguidores de calidad mundial para tu cuenta. Incluye 2.000 Likes y 2.000 Visitas de regalo. Con 30 días de garantía ante caídas (1% ~ 5%).`,
    longDescription: `Aumenta tu credibilidad en Instagram con seguidores de calidad mundial. Este paquete incluye 10.000 seguidores reales y activos que se entregarán de forma gradual para mantener la naturalidad de tu cuenta. Como BONUS, recibirás 2.000 likes y 2.000 visitas para tus publicaciones. Todos nuestros seguidores de calidad incluyen 30 días de garantía ante caídas (solo 1% ~ 5%).`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 120000,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 5.0,
    platform: "instagram",
    category: "seguidores-calidad",
    features: [
      "10.000 seguidores reales y activos",
      "BONUS: 2.000 likes para tus publicaciones",
      "BONUS: 2.000 visitas para tus publicaciones",
      "Entrega gradual y natural",
      "30 días de garantía",
      "Caídas mínimas (1-5%)",
      "Soporte 24/7",
    ],
  },

  // SEGUIDORES MUNDIALES INSTAGRAM
  {
    id: 201,
    title: "100 Seguidores Mundiales",
    description: `Seguidores mundiales para tu cuenta de Instagram. ${advertenciaText}`,
    longDescription: `Aumenta rápidamente tus seguidores en Instagram con este paquete de 100 seguidores mundiales. Este servicio es ideal para quienes buscan incrementar su número de seguidores a un precio accesible. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 900,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.5,
    platform: "instagram",
    category: "seguidores-mundiales",
    features: [
      "100 seguidores mundiales",
      "Entrega rápida",
      "Precio accesible",
      "Sin requisitos de privacidad",
      "Soporte 24/7",
    ],
  },
  {
    id: 202,
    title: "250 Seguidores Mundiales",
    description: `Seguidores mundiales para tu cuenta de Instagram. ${advertenciaText}`,
    longDescription: `Aumenta rápidamente tus seguidores en Instagram con este paquete de 250 seguidores mundiales. Este servicio es ideal para quienes buscan incrementar su número de seguidores a un precio accesible. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 1500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.5,
    platform: "instagram",
    category: "seguidores-mundiales",
    features: [
      "250 seguidores mundiales",
      "Entrega rápida",
      "Precio accesible",
      "Sin requisitos de privacidad",
      "Soporte 24/7",
    ],
  },
  {
    id: 203,
    title: "500 Seguidores Mundiales",
    description: `Seguidores mundiales para tu cuenta de Instagram. ${advertenciaText}`,
    longDescription: `Aumenta rápidamente tus seguidores en Instagram con este paquete de 500 seguidores mundiales. Este servicio es ideal para quienes buscan incrementar su número de seguidores a un precio accesible. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 2500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.6,
    platform: "instagram",
    category: "seguidores-mundiales",
    features: [
      "500 seguidores mundiales",
      "Entrega rápida",
      "Precio accesible",
      "Sin requisitos de privacidad",
      "Soporte 24/7",
    ],
  },
  {
    id: 204,
    title: "1.000 Seguidores Mundiales",
    description: `Seguidores mundiales para tu cuenta de Instagram. ${advertenciaText}`,
    longDescription: `Aumenta rápidamente tus seguidores en Instagram con este paquete de 1.000 seguidores mundiales. Este servicio es ideal para quienes buscan incrementar su número de seguidores a un precio accesible. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 4500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.7,
    platform: "instagram",
    category: "seguidores-mundiales",
    features: [
      "1.000 seguidores mundiales",
      "Entrega rápida",
      "Precio accesible",
      "Sin requisitos de privacidad",
      "Soporte 24/7",
    ],
  },
  {
    id: 205,
    title: "2.500 Seguidores Mundiales",
    description: `Seguidores mundiales para tu cuenta de Instagram. Incluye 250 Likes de regalo. ${advertenciaText}`,
    longDescription: `Aumenta rápidamente tus seguidores en Instagram con este paquete de 2.500 seguidores mundiales. Como BONUS, recibirás 250 likes para tus publicaciones. Este servicio es ideal para quienes buscan incrementar su número de seguidores a un precio accesible. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 9500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.7,
    platform: "instagram",
    category: "seguidores-mundiales",
    features: [
      "2.500 seguidores mundiales",
      "BONUS: 250 likes para tus publicaciones",
      "Entrega rápida",
      "Precio accesible",
      "Sin requisitos de privacidad",
      "Soporte 24/7",
    ],
  },
  {
    id: 206,
    title: "5.000 Seguidores Mundiales",
    description: `Seguidores mundiales para tu cuenta de Instagram. Incluye 500 Likes de regalo. ${advertenciaText}`,
    longDescription: `Aumenta rápidamente tus seguidores en Instagram con este paquete de 5.000 seguidores mundiales. Como BONUS, recibirás 500 likes para tus publicaciones. Este servicio es ideal para quienes buscan incrementar su número de seguidores a un precio accesible. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 18000,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.8,
    platform: "instagram",
    category: "seguidores-mundiales",
    features: [
      "5.000 seguidores mundiales",
      "BONUS: 500 likes para tus publicaciones",
      "Entrega rápida",
      "Precio accesible",
      "Sin requisitos de privacidad",
      "Soporte 24/7",
    ],
  },
  {
    id: 207,
    title: "8.000 Seguidores Mundiales",
    description: `Seguidores mundiales para tu cuenta de Instagram. Incluye 1.000 Likes y 1.000 Visitas de regalo. ${advertenciaText}`,
    longDescription: `Aumenta rápidamente tus seguidores en Instagram con este paquete de 8.000 seguidores mundiales. Como BONUS, recibirás 1.000 likes y 1.000 visitas para tus publicaciones. Este servicio es ideal para quienes buscan incrementar su número de seguidores a un precio accesible. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 23000,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.8,
    platform: "instagram",
    category: "seguidores-mundiales",
    features: [
      "8.000 seguidores mundiales",
      "BONUS: 1.000 likes para tus publicaciones",
      "BONUS: 1.000 visitas para tus publicaciones",
      "Entrega rápida",
      "Precio accesible",
      "Sin requisitos de privacidad",
      "Soporte 24/7",
    ],
  },
  {
    id: 208,
    title: "10.000 Seguidores Mundiales",
    description: `Seguidores mundiales para tu cuenta de Instagram. Incluye 2.000 Likes y 2.000 Visitas de regalo. ${advertenciaText}`,
    longDescription: `Aumenta rápidamente tus seguidores en Instagram con este paquete de 10.000 seguidores mundiales. Como BONUS, recibirás 2.000 likes y 2.000 visitas para tus publicaciones. Este servicio es ideal para quienes buscan incrementar su número de seguidores a un precio accesible. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 25000,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.9,
    platform: "instagram",
    category: "seguidores-mundiales",
    features: [
      "10.000 seguidores mundiales",
      "BONUS: 2.000 likes para tus publicaciones",
      "BONUS: 2.000 visitas para tus publicaciones",
      "Entrega rápida",
      "Precio accesible",
      "Sin requisitos de privacidad",
      "Soporte 24/7",
    ],
  },

  // LIKES MUNDIALES INSTAGRAM
  {
    id: 301,
    title: "100 Likes Mundiales",
    description: `Likes mundiales para tus publicaciones de Instagram. ${advertenciaText}`,
    longDescription: `Aumenta el engagement de tus publicaciones con este paquete de 100 likes mundiales para Instagram. Este servicio es ideal para mejorar la visibilidad de tus posts y atraer más interacción. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.5,
    platform: "instagram",
    category: "likes-mundiales",
    features: [
      "100 likes mundiales",
      "Entrega rápida",
      "Aplicable a cualquier publicación",
      "Mejora la visibilidad de tus posts",
      "Soporte 24/7",
    ],
  },
  {
    id: 302,
    title: "250 Likes Mundiales",
    description: `Likes mundiales para tus publicaciones de Instagram. ${advertenciaText}`,
    longDescription: `Aumenta el engagement de tus publicaciones con este paquete de 250 likes mundiales para Instagram. Este servicio es ideal para mejorar la visibilidad de tus posts y atraer más interacción. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 750,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.6,
    platform: "instagram",
    category: "likes-mundiales",
    features: [
      "250 likes mundiales",
      "Entrega rápida",
      "Aplicable a cualquier publicación",
      "Mejora la visibilidad de tus posts",
      "Soporte 24/7",
    ],
  },
  {
    id: 303,
    title: "500 Likes Mundiales",
    description: `Likes mundiales para tus publicaciones de Instagram. ${advertenciaText}`,
    longDescription: `Aumenta el engagement de tus publicaciones con este paquete de 500 likes mundiales para Instagram. Este servicio es ideal para mejorar la visibilidad de tus posts y atraer más interacción. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 1000,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.7,
    platform: "instagram",
    category: "likes-mundiales",
    features: [
      "500 likes mundiales",
      "Entrega rápida",
      "Aplicable a cualquier publicación",
      "Mejora la visibilidad de tus posts",
      "Soporte 24/7",
    ],
  },
  {
    id: 304,
    title: "1.000 Likes Mundiales",
    description: `Likes mundiales para tus publicaciones de Instagram. ${advertenciaText}`,
    longDescription: `Aumenta el engagement de tus publicaciones con este paquete de 1.000 likes mundiales para Instagram. Este servicio es ideal para mejorar la visibilidad de tus posts y atraer más interacción. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 1500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.8,
    platform: "instagram",
    category: "likes-mundiales",
    features: [
      "1.000 likes mundiales",
      "Entrega rápida",
      "Aplicable a cualquier publicación",
      "Mejora la visibilidad de tus posts",
      "Soporte 24/7",
    ],
  },
  {
    id: 305,
    title: "2.500 Likes Mundiales",
    description: `Likes mundiales para tus publicaciones de Instagram. ${advertenciaText}`,
    longDescription: `Aumenta el engagement de tus publicaciones con este paquete de 2.500 likes mundiales para Instagram. Este servicio es ideal para mejorar la visibilidad de tus posts y atraer más interacción. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 2000,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.8,
    platform: "instagram",
    category: "likes-mundiales",
    features: [
      "2.500 likes mundiales",
      "Entrega rápida",
      "Aplicable a cualquier publicación",
      "Mejora la visibilidad de tus posts",
      "Soporte 24/7",
    ],
  },
  {
    id: 306,
    title: "5.000 Likes Mundiales",
    description: `Likes mundiales para tus publicaciones de Instagram. ${advertenciaText}`,
    longDescription: `Aumenta el engagement de tus publicaciones con este paquete de 5.000 likes mundiales para Instagram. Este servicio es ideal para mejorar la visibilidad de tus posts y atraer más interacción. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 3000,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.9,
    platform: "instagram",
    category: "likes-mundiales",
    features: [
      "5.000 likes mundiales",
      "Entrega rápida",
      "Aplicable a cualquier publicación",
      "Mejora la visibilidad de tus posts",
      "Soporte 24/7",
    ],
  },
  {
    id: 307,
    title: "10.000 Likes Mundiales",
    description: `Likes mundiales para tus publicaciones de Instagram. ${advertenciaText}`,
    longDescription: `Aumenta el engagement de tus publicaciones con este paquete de 10.000 likes mundiales para Instagram. Este servicio es ideal para mejorar la visibilidad de tus posts y atraer más interacción. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 4500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 5.0,
    platform: "instagram",
    category: "likes-mundiales",
    features: [
      "10.000 likes mundiales",
      "Entrega rápida",
      "Aplicable a cualquier publicación",
      "Mejora la visibilidad de tus posts",
      "Soporte 24/7",
    ],
  },

  // VISITAS MUNDIALES INSTAGRAM
  {
    id: 401,
    title: "500 Visitas Mundiales",
    description: `Visitas mundiales para tus publicaciones de Instagram. ${advertenciaText}`,
    longDescription: `Aumenta el alcance de tus publicaciones con este paquete de 500 visitas mundiales para Instagram. Este servicio es ideal para mejorar la visibilidad de tus posts y aumentar su alcance en el algoritmo. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 250,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.5,
    platform: "instagram",
    category: "visitas-mundiales",
    features: [
      "500 visitas mundiales",
      "Entrega rápida",
      "Aplicable a cualquier publicación",
      "Mejora el alcance de tus posts",
      "Soporte 24/7",
    ],
  },
  {
    id: 402,
    title: "1.000 Visitas Mundiales",
    description: `Visitas mundiales para tus publicaciones de Instagram. ${advertenciaText}`,
    longDescription: `Aumenta el alcance de tus publicaciones con este paquete de 1.000 visitas mundiales para Instagram. Este servicio es ideal para mejorar la visibilidad de tus posts y aumentar su alcance en el algoritmo. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.6,
    platform: "instagram",
    category: "visitas-mundiales",
    features: [
      "1.000 visitas mundiales",
      "Entrega rápida",
      "Aplicable a cualquier publicación",
      "Mejora el alcance de tus posts",
      "Soporte 24/7",
    ],
  },
  {
    id: 403,
    title: "2.500 Visitas Mundiales",
    description: `Visitas mundiales para tus publicaciones de Instagram. ${advertenciaText}`,
    longDescription: `Aumenta el alcance de tus publicaciones con este paquete de 2.500 visitas mundiales para Instagram. Este servicio es ideal para mejorar la visibilidad de tus posts y aumentar su alcance en el algoritmo. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 1500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.7,
    platform: "instagram",
    category: "visitas-mundiales",
    features: [
      "2.500 visitas mundiales",
      "Entrega rápida",
      "Aplicable a cualquier publicación",
      "Mejora el alcance de tus posts",
      "Soporte 24/7",
    ],
  },
  {
    id: 404,
    title: "5.000 Visitas Mundiales",
    description: `Visitas mundiales para tus publicaciones de Instagram. ${advertenciaText}`,
    longDescription: `Aumenta el alcance de tus publicaciones con este paquete de 5.000 visitas mundiales para Instagram. Este servicio es ideal para mejorar la visibilidad de tus posts y aumentar su alcance en el algoritmo. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 2500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.8,
    platform: "instagram",
    category: "visitas-mundiales",
    features: [
      "5.000 visitas mundiales",
      "Entrega rápida",
      "Aplicable a cualquier publicación",
      "Mejora el alcance de tus posts",
      "Soporte 24/7",
    ],
  },

  // VISITAS A HISTORIAS
  {
    id: 501,
    title: "100 Visitas a Historias",
    description: `Visitas para tus historias de Instagram. ${advertenciaText}`,
    longDescription: `Aumenta la visibilidad de tus historias con este paquete de 100 visitas para historias de Instagram. Este servicio es ideal para mejorar la visibilidad de tus historias y aumentar tu engagement. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 150,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.5,
    platform: "instagram",
    category: "visitas-historias",
    features: [
      "100 visitas a historias",
      "Entrega rápida",
      "Aplicable a cualquier historia",
      "Mejora la visibilidad de tus historias",
      "Soporte 24/7",
    ],
  },
  {
    id: 502,
    title: "250 Visitas a Historias",
    description: `Visitas para tus historias de Instagram. ${advertenciaText}`,
    longDescription: `Aumenta la visibilidad de tus historias con este paquete de 250 visitas para historias de Instagram. Este servicio es ideal para mejorar la visibilidad de tus historias y aumentar tu engagement. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 400,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.6,
    platform: "instagram",
    category: "visitas-historias",
    features: [
      "250 visitas a historias",
      "Entrega rápida",
      "Aplicable a cualquier historia",
      "Mejora la visibilidad de tus historias",
      "Soporte 24/7",
    ],
  },
  {
    id: 503,
    title: "500 Visitas a Historias",
    description: `Visitas para tus historias de Instagram. ${advertenciaText}`,
    longDescription: `Aumenta la visibilidad de tus historias con este paquete de 500 visitas para historias de Instagram. Este servicio es ideal para mejorar la visibilidad de tus historias y aumentar tu engagement. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 800,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.7,
    platform: "instagram",
    category: "visitas-historias",
    features: [
      "500 visitas a historias",
      "Entrega rápida",
      "Aplicable a cualquier historia",
      "Mejora la visibilidad de tus historias",
      "Soporte 24/7",
    ],
  },
  {
    id: 504,
    title: "1.000 Visitas a Historias",
    description: `Visitas para tus historias de Instagram. ${advertenciaText}`,
    longDescription: `Aumenta la visibilidad de tus historias con este paquete de 1.000 visitas para historias de Instagram. Este servicio es ideal para mejorar la visibilidad de tus historias y aumentar tu engagement. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 1500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.8,
    platform: "instagram",
    category: "visitas-historias",
    features: [
      "1.000 visitas a historias",
      "Entrega rápida",
      "Aplicable a cualquier historia",
      "Mejora la visibilidad de tus historias",
      "Soporte 24/7",
    ],
  },
  {
    id: 505,
    title: "2.500 Visitas a Historias",
    description: `Visitas para tus historias de Instagram. ${advertenciaText}`,
    longDescription: `Aumenta la visibilidad de tus historias con este paquete de 2.500 visitas para historias de Instagram. Este servicio es ideal para mejorar la visibilidad de tus historias y aumentar tu engagement. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 3500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.9,
    platform: "instagram",
    category: "visitas-historias",
    features: [
      "2.500 visitas a historias",
      "Entrega rápida",
      "Aplicable a cualquier historia",
      "Mejora la visibilidad de tus historias",
      "Soporte 24/7",
    ],
  },
  {
    id: 506,
    title: "5.000 Visitas a Historias",
    description: `Visitas para tus historias de Instagram. ${advertenciaText}`,
    longDescription: `Aumenta la visibilidad de tus historias con este paquete de 5.000 visitas para historias de Instagram. Este servicio es ideal para mejorar la visibilidad de tus historias y aumentar tu engagement. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 6000,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 5.0,
    platform: "instagram",
    category: "visitas-historias",
    features: [
      "5.000 visitas a historias",
      "Entrega rápida",
      "Aplicable a cualquier historia",
      "Mejora la visibilidad de tus historias",
      "Soporte 24/7",
    ],
  },

  // GUARDADOS DE POST
  {
    id: 601,
    title: "250 Guardados de Post",
    description: `Guardados para tus publicaciones de Instagram. ${advertenciaText}`,
    longDescription: `Aumenta el alcance de tus publicaciones con este paquete de 250 guardados para posts de Instagram. Los guardados son una señal importante para el algoritmo de Instagram y pueden ayudar a que tus publicaciones aparezcan en más feeds. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 400,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.6,
    platform: "instagram",
    category: "guardados",
    features: [
      "250 guardados de post",
      "Entrega rápida",
      "Aplicable a cualquier publicación",
      "Mejora el alcance de tus posts",
      "Soporte 24/7",
    ],
  },
  {
    id: 602,
    title: "500 Guardados de Post",
    description: `Guardados para tus publicaciones de Instagram. ${advertenciaText}`,
    longDescription: `Aumenta el alcance de tus publicaciones con este paquete de 500 guardados para posts de Instagram. Los guardados son una señal importante para el algoritmo de Instagram y pueden ayudar a que tus publicaciones aparezcan en más feeds. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 800,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.7,
    platform: "instagram",
    category: "guardados",
    features: [
      "500 guardados de post",
      "Entrega rápida",
      "Aplicable a cualquier publicación",
      "Mejora el alcance de tus posts",
      "Soporte 24/7",
    ],
  },
  {
    id: 603,
    title: "1.000 Guardados de Post",
    description: `Guardados para tus publicaciones de Instagram. ${advertenciaText}`,
    longDescription: `Aumenta el alcance de tus publicaciones con este paquete de 1.000 guardados para posts de Instagram. Los guardados son una señal importante para el algoritmo de Instagram y pueden ayudar a que tus publicaciones aparezcan en más feeds. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 1500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.8,
    platform: "instagram",
    category: "guardados",
    features: [
      "1.000 guardados de post",
      "Entrega rápida",
      "Aplicable a cualquier publicación",
      "Mejora el alcance de tus posts",
      "Soporte 24/7",
    ],
  },
  {
    id: 604,
    title: "2.500 Guardados de Post",
    description: `Guardados para tus publicaciones de Instagram. ${advertenciaText}`,
    longDescription: `Aumenta el alcance de tus publicaciones con este paquete de 2.500 guardados para posts de Instagram. Los guardados son una señal importante para el algoritmo de Instagram y pueden ayudar a que tus publicaciones aparezcan en más feeds. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 3500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.9,
    platform: "instagram",
    category: "guardados",
    features: [
      "2.500 guardados de post",
      "Entrega rápida",
      "Aplicable a cualquier publicación",
      "Mejora el alcance de tus posts",
      "Soporte 24/7",
    ],
  },
  {
    id: 605,
    title: "5.000 Guardados de Post",
    description: `Guardados para tus publicaciones de Instagram. ${advertenciaText}`,
    longDescription: `Aumenta el alcance de tus publicaciones con este paquete de 5.000 guardados para posts de Instagram. Los guardados son una señal importante para el algoritmo de Instagram y pueden ayudar a que tus publicaciones aparezcan en más feeds. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 6000,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 5.0,
    platform: "instagram",
    category: "guardados",
    features: [
      "5.000 guardados de post",
      "Entrega rápida",
      "Aplicable a cualquier publicación",
      "Mejora el alcance de tus posts",
      "Soporte 24/7",
    ],
  },

  // COMENTARIOS RANDOM
  {
    id: 701,
    title: "10 Comentarios Random",
    description: `Comentarios aleatorios positivos para tus publicaciones. ${advertenciaText}`,
    longDescription: `Aumenta el engagement de tus publicaciones con este paquete de 10 comentarios aleatorios positivos para tus posts de Instagram. Los comentarios son una señal importante para el algoritmo y pueden ayudar a generar más interacción en tus publicaciones. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 2000,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.7,
    platform: "instagram",
    category: "comentarios",
    features: [
      "10 comentarios aleatorios positivos",
      "Entrega rápida",
      "Aplicable a cualquier publicación",
      "Mejora el engagement de tus posts",
      "Soporte 24/7",
    ],
  },
  {
    id: 702,
    title: "50 Comentarios Random",
    description: `Comentarios aleatorios positivos para tus publicaciones. ${advertenciaText}`,
    longDescription: `Aumenta el engagement de tus publicaciones con este paquete de 50 comentarios aleatorios positivos para tus posts de Instagram. Los comentarios son una señal importante para el algoritmo y pueden ayudar a generar más interacción en tus publicaciones. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 4500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.8,
    platform: "instagram",
    category: "comentarios",
    features: [
      "50 comentarios aleatorios positivos",
      "Entrega rápida",
      "Aplicable a cualquier publicación",
      "Mejora el engagement de tus posts",
      "Soporte 24/7",
    ],
  },
  {
    id: 703,
    title: "100 Comentarios Random",
    description: `Comentarios aleatorios positivos para tus publicaciones. ${advertenciaText}`,
    longDescription: `Aumenta el engagement de tus publicaciones con este paquete de 100 comentarios aleatorios positivos para tus posts de Instagram. Los comentarios son una señal importante para el algoritmo y pueden ayudar a generar más interacción en tus publicaciones. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 7500,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 4.9,
    platform: "instagram",
    category: "comentarios",
    features: [
      "100 comentarios aleatorios positivos",
      "Entrega rápida",
      "Aplicable a cualquier publicación",
      "Mejora el engagement de tus posts",
      "Soporte 24/7",
    ],
  },
  {
    id: 704,
    title: "500 Comentarios Random",
    description: `Comentarios aleatorios positivos para tus publicaciones. ${advertenciaText}`,
    longDescription: `Aumenta el engagement de tus publicaciones con este paquete de 500 comentarios aleatorios positivos para tus posts de Instagram. Los comentarios son una señal importante para el algoritmo y pueden ayudar a generar más interacción en tus publicaciones. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 15000,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 5.0,
    platform: "instagram",
    category: "comentarios",
    features: [
      "500 comentarios aleatorios positivos",
      "Entrega rápida",
      "Aplicable a cualquier publicación",
      "Mejora el engagement de tus posts",
      "Soporte 24/7",
    ],
  },
  {
    id: 705,
    title: "1.000 Comentarios Random",
    description: `Comentarios aleatorios positivos para tus publicaciones. ${advertenciaText}`,
    longDescription: `Aumenta el engagement de tus publicaciones con este paquete de 1.000 comentarios aleatorios positivos para tus posts de Instagram. Los comentarios son una señal importante para el algoritmo y pueden ayudar a generar más interacción en tus publicaciones. ${advertenciaText}`,
    srcUrl: instagramImage,
    gallery: [instagramImage],
    price: 25000,
    discount: {
      amount: 0,
      percentage: 0,
    },
    rating: 5.0,
    platform: "instagram",
    category: "comentarios",
    features: [
      "1.000 comentarios aleatorios positivos",
      "Entrega rápida",
      "Aplicable a cualquier publicación",
      "Mejora el engagement de tus posts",
      "Soporte 24/7",
    ],
  },
]

// Categorías de servicios de Instagram
export const instagramCategories = [
  { id: "seguidores-calidad", name: "Seguidores de Calidad" },
  { id: "seguidores-mundiales", name: "Seguidores Mundiales" },
  { id: "likes-mundiales", name: "Likes Mundiales" },
  { id: "visitas-mundiales", name: "Visitas Mundiales" },
  { id: "visitas-historias", name: "Visitas a Historias" },
  { id: "guardados", name: "Guardados de Post" },
  { id: "comentarios", name: "Comentarios Random" },
]

// Obtener productos por categoría
export const getProductsByCategory = (category: string) => {
  return instagramServicesData.filter((product) => product.category === category)
}

// Obtener un producto por ID
export const getProductById = (id: number) => {
  return instagramServicesData.find((product) => product.id === id)
}

